name: Generate CCB Agenda

on:
  push:
  pull_request:

jobs:
  #Checks for duplicate actions. Skips push actions if there is a matching or duplicate pull-request action. 
  check-for-duplicates:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
        should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  generate-agenda:
    #Continue if check-for-duplicates found no duplicates. Always runs for pull-requests.
    needs: check-for-duplicates
    if: ${{ needs.check-for-duplicates.outputs.should_skip != 'true' }}
    name: Generate Agenda
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

    steps:      
      - name: Install ruby
        run: |
          sudo apt-get install ruby-full -y
          gem install export-pull-requests

      - name: Checkout code
        run: epr -l CCB:Ready -x pr ArielSAdams/cFS > agenda.csv

      - name: Archive static analysis artifacts
        uses: actions/upload-artifact@v2
        with:
          name: agenda.csv
